services:
  - type: web
    name: kampot-dog-sanctuary
    runtime: static
    buildCommand: cd Client && npm ci && npm run build
    staticPublishPath: Client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
